# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "cloud.google.com/go";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/gocloud";
      rev = "3b1ae45394a234c385be014e9a488f2bb6eef821";
      sha256 = "0alb495ql6s02kb6lxcbnlkdcmhixyl8zv11sgrkhsk1bckzh119";
    };
  }
  {
    goPackagePath = "github.com/Azure/go-autorest";
    fetch = {
      type = "git";
      url = "https://github.com/Azure/go-autorest";
      rev = "58f6f26e200fa5dfb40c9cd1c83f3e2c860d779d";
      sha256 = "06zzkw0x8sv57x0fi0chcn9zm5qq69spbsa02d0zdlzh2bd74x6f";
    };
  }
  {
    goPackagePath = "github.com/PuerkitoBio/purell";
    fetch = {
      type = "git";
      url = "https://github.com/PuerkitoBio/purell";
      rev = "8a290539e2e8629dbc4e6bad948158f790ec31f4";
      sha256 = "1qhsy1nm96b9kb63svkvkqmmw15xg6irwcysisxdgzk64adfwqv1";
    };
  }
  {
    goPackagePath = "github.com/PuerkitoBio/urlesc";
    fetch = {
      type = "git";
      url = "https://github.com/PuerkitoBio/urlesc";
      rev = "5bd2802263f21d8788851d5305584c82a5c75d7e";
      sha256 = "15y5r3asvm7196m3nza5xvdvlc2k11p6lfs6hi917hl7r9vgi6mp";
    };
  }
  {
    goPackagePath = "github.com/beorn7/perks";
    fetch = {
      type = "git";
      url = "https://github.com/beorn7/perks";
      rev = "3ac7bf7a47d159a033b107610db8a1b6575507a4";
      sha256 = "1qc3l4r818xpvrhshh1sisc5lvl9479qspcfcdbivdyh0apah83r";
    };
  }
  {
    goPackagePath = "github.com/coreos/etcd";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/etcd";
      rev = "c23606781f63d09917a1e7abfcefeb337a9608ea";
      sha256 = "0fgwidy7kbsynxz9q7bkrh56s29yg32ik6vibdlsy78xdda9mlwm";
    };
  }
  {
    goPackagePath = "github.com/coreos/go-semver";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/go-semver";
      rev = "8ab6407b697782a06568d4b7f1db25550ec2e4c6";
      sha256 = "1gghi5bnqj50hfxhqc1cxmynqmh2yk9ii7ab9gsm75y5cp94ymk0";
    };
  }
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "782f4967f2dc4564575ca782fe2d04090b5faca8";
      sha256 = "1ypijjawqc0xgmgim42260ibcyclfgfizicz5cbvndw4plqfsswk";
    };
  }
  {
    goPackagePath = "github.com/dgrijalva/jwt-go";
    fetch = {
      type = "git";
      url = "https://github.com/dgrijalva/jwt-go";
      rev = "d2709f9f1f31ebcda9651b03077758c1f3a0018c";
      sha256 = "02zhyimshzfzp3by2lggm2z382j4pvbrbcxx9p1wqmmmwy5yz182";
    };
  }
  {
    goPackagePath = "github.com/emicklei/go-restful";
    fetch = {
      type = "git";
      url = "https://github.com/emicklei/go-restful";
      rev = "ff4f55a206334ef123e4f79bbf348980da81ca46";
      sha256 = "1v5lj5142abz3gvbygp6xghpdx4ps2lwswl8559ivaidahwnc21c";
    };
  }
  {
    goPackagePath = "github.com/emicklei/go-restful-swagger12";
    fetch = {
      type = "git";
      url = "https://github.com/emicklei/go-restful-swagger12";
      rev = "dcef7f55730566d41eae5db10e7d6981829720f6";
      sha256 = "0zz1f6n1qfbyrp592mgyrkyfhki3r0ksic6ja9lxisg8br1ibrvq";
    };
  }
  {
    goPackagePath = "github.com/ghodss/yaml";
    fetch = {
      type = "git";
      url = "https://github.com/ghodss/yaml";
      rev = "0ca9ea5df5451ffdf184b4428c902747c2c11cd7";
      sha256 = "0skwmimpy7hlh7pva2slpcplnm912rp3igs98xnqmn859kwa5v8g";
    };
  }
  {
    goPackagePath = "github.com/go-openapi/jsonpointer";
    fetch = {
      type = "git";
      url = "https://github.com/go-openapi/jsonpointer";
      rev = "46af16f9f7b149af66e5d1bd010e3574dc06de98";
      sha256 = "0w0fphmdycjzbsm1vppdcjc9aqinkcdzcq3pxikdvdqh5p791gsc";
    };
  }
  {
    goPackagePath = "github.com/go-openapi/jsonreference";
    fetch = {
      type = "git";
      url = "https://github.com/go-openapi/jsonreference";
      rev = "13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272";
      sha256 = "1fh4xcl9ijww4bdq656sx981d57w2c9zx5148jsxlsg4bsvxmwis";
    };
  }
  {
    goPackagePath = "github.com/go-openapi/spec";
    fetch = {
      type = "git";
      url = "https://github.com/go-openapi/spec";
      rev = "7abd5745472fff5eb3685386d5fb8bf38683154d";
      sha256 = "1z9hwfzxgwr59r1syy0s4hgybs27q87n9mm1bbxl0yl5yvzw67rl";
    };
  }
  {
    goPackagePath = "github.com/go-openapi/swag";
    fetch = {
      type = "git";
      url = "https://github.com/go-openapi/swag";
      rev = "f3f9494671f93fcff853e3c6e9e948b3eb71e590";
      sha256 = "13lqn4xqy9vma9aqsjb0fzfzi0q8l6dmg65sjxqdxf3q6gzkvmjy";
    };
  }
  {
    goPackagePath = "github.com/gogo/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/gogo/protobuf";
      rev = "342cbe0a04158f6dcb03ca0079991a51a4248c02";
      sha256 = "1pp1ghicii6f80ygchjqzqswrycpyqhc0m08lrhzyz77ck39cl4q";
    };
  }
  {
    goPackagePath = "github.com/golang/glog";
    fetch = {
      type = "git";
      url = "https://github.com/golang/glog";
      rev = "44145f04b68cf362d9c4df2182967c2275eaefed";
      sha256 = "1k7sf6qmpgm0iw81gx2dwggf9di6lgw0n54mni7862hihwfrb5rq";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "1e59b77b52bf8e4b449a57e6f79f21226d571845";
      sha256 = "19bkh81wnp6njg3931wky6hsnnl2d1ig20vfjxpv450sd3k6yys8";
    };
  }
  {
    goPackagePath = "github.com/google/btree";
    fetch = {
      type = "git";
      url = "https://github.com/google/btree";
      rev = "925471ac9e2131377a91e1595defec898166fe49";
      sha256 = "1z5zmqi34xw0gn5iscdbpz7wmr84g3m2c2lwslm4623a7j5hl1f4";
    };
  }
  {
    goPackagePath = "github.com/google/gofuzz";
    fetch = {
      type = "git";
      url = "https://github.com/google/gofuzz";
      rev = "44d81051d367757e1c7c6a5a86423ece9afcf63c";
      sha256 = "0ivq2sl2fv8x0xxrcys27c42s8yq7irgl7lp6l0im9i7ky63nk0i";
    };
  }
  {
    goPackagePath = "github.com/googleapis/gnostic";
    fetch = {
      type = "git";
      url = "https://github.com/googleapis/gnostic";
      rev = "0c5108395e2debce0d731cf0287ddf7242066aba";
      sha256 = "0jf3cp5clli88gpjf24r6wxbkvngnc1kf59d4cgjczsn2wasvsfc";
    };
  }
  {
    goPackagePath = "github.com/gophercloud/gophercloud";
    fetch = {
      type = "git";
      url = "https://github.com/gophercloud/gophercloud";
      rev = "443743e88335413103dcf1997e46d401b264fbcd";
      sha256 = "0fsf40pnyisk36k4bgzwrkj1g7cczm6wv3fkw919x2dcf99p1zwj";
    };
  }
  {
    goPackagePath = "github.com/gregjones/httpcache";
    fetch = {
      type = "git";
      url = "https://github.com/gregjones/httpcache";
      rev = "787624de3eb7bd915c329cba748687a3b22666a6";
      sha256 = "1zqlg9pkj7r6fqw7wv3ywvbz3bh0hvzifs2scgcraj812q5189w5";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/golang-lru";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/golang-lru";
      rev = "a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4";
      sha256 = "1z3h4aca31l3qs0inqr5l49vrlycpjm7vq1l9nh1mp0mb2ij0kmp";
    };
  }
  {
    goPackagePath = "github.com/howeyc/gopass";
    fetch = {
      type = "git";
      url = "https://github.com/howeyc/gopass";
      rev = "bf9dde6d0d2c004a008c27aaee91170c786f6db8";
      sha256 = "1jxzyfnqi0h1fzlsvlkn10bncic803bfhslyijcxk55mgh297g45";
    };
  }
  {
    goPackagePath = "github.com/imdario/mergo";
    fetch = {
      type = "git";
      url = "https://github.com/imdario/mergo";
      rev = "6633656539c1639d9d78127b7d47c622b5d7b6dc";
      sha256 = "1fffbq1l17i0gynmvcxypl7d9h4v81g5vlimiph5bfgf4sp4db7g";
    };
  }
  {
    goPackagePath = "github.com/json-iterator/go";
    fetch = {
      type = "git";
      url = "https://github.com/json-iterator/go";
      rev = "36b14963da70d11297d313183d7e6388c8510e1e";
      sha256 = "143sz8ld4w3798iwdg1wxyqdks3wskdasy3fhrzfnqx1ayifr3fh";
    };
  }
  {
    goPackagePath = "github.com/juju/ratelimit";
    fetch = {
      type = "git";
      url = "https://github.com/juju/ratelimit";
      rev = "5b9ff866471762aa2ab2dced63c9fb6f53921342";
      sha256 = "12fsx3wqg49wisigbybdzic7gc2p5a0fk55714mpv7zq8jr6i46k";
    };
  }
  {
    goPackagePath = "github.com/kelseyhightower/envconfig";
    fetch = {
      type = "git";
      url = "https://github.com/kelseyhightower/envconfig";
      rev = "f611eb38b3875cc3bd991ca91c51d06446afa14c";
      sha256 = "1zcq480ig7wbg4378qcfxznp2gzqmk7x6rbxizflvg9v2f376vrw";
    };
  }
  {
    goPackagePath = "github.com/mailru/easyjson";
    fetch = {
      type = "git";
      url = "https://github.com/mailru/easyjson";
      rev = "2f5df55504ebc322e4d52d34df6a1f5b503bf26d";
      sha256 = "0d9m8kyhbawa452vnwn255xxnh6pkp3im0d2310rw1k14nh3yh1p";
    };
  }
  {
    goPackagePath = "github.com/matttproud/golang_protobuf_extensions";
    fetch = {
      type = "git";
      url = "https://github.com/matttproud/golang_protobuf_extensions";
      rev = "fc2b8d3a73c4867e51861bbdd5ae3c1f0869dd6a";
      sha256 = "0ajg41h6402big484drvm72wvid1af2sffw0qkzbmpy04lq68ahj";
    };
  }
  {
    goPackagePath = "github.com/onsi/ginkgo";
    fetch = {
      type = "git";
      url = "https://github.com/onsi/ginkgo";
      rev = "fa5fabab2a1bfbd924faf4c067d07ae414e2aedf";
      sha256 = "1q6431prnrarwlg4p7bfzn64rbx40n91j8673jmzmmbnp28qvskb";
    };
  }
  {
    goPackagePath = "github.com/onsi/gomega";
    fetch = {
      type = "git";
      url = "https://github.com/onsi/gomega";
      rev = "62bff4df71bdbc266561a0caee19f0594b17c240";
      sha256 = "12rpmq7vx2p7wzrqbk1cs655rpip4kja2csi3halpn8x6bk1xjj4";
    };
  }
  {
    goPackagePath = "github.com/patrickmn/go-cache";
    fetch = {
      type = "git";
      url = "https://github.com/patrickmn/go-cache";
      rev = "9f6ff22cfff829561052f5886ec80a2ac148b4eb";
      sha256 = "0f7pqh8mi4hwz1xxr6yl90x25lr99sz5ga66igf40rb09g2806c7";
    };
  }
  {
    goPackagePath = "github.com/pborman/uuid";
    fetch = {
      type = "git";
      url = "https://github.com/pborman/uuid";
      rev = "ca53cad383cad2479bbba7f7a1a05797ec1386e4";
      sha256 = "0rcx669bbjkkwdlw81spnra4ffgzd4rbpywnrj3w41m9vq6mk1gn";
    };
  }
  {
    goPackagePath = "github.com/peterbourgon/diskv";
    fetch = {
      type = "git";
      url = "https://github.com/peterbourgon/diskv";
      rev = "5f041e8faa004a95c88a202771f4cc3e991971e6";
      sha256 = "1mxpa5aad08x30qcbffzk80g9540wvbca4blc1r2qyzl65b8929b";
    };
  }
  {
    goPackagePath = "github.com/projectcalico/felix";
    fetch = {
      type = "git";
      url = "https://github.com/projectcalico/felix";
      rev = "518dbc352494a962e46d50f8bfe72a70c86951bf";
      sha256 = "07603dz8cj91yv2iz04anljp3dxzn5vf21mnf3v3xky2ikdffiil";
    };
  }
  {
    goPackagePath = "github.com/projectcalico/go-json";
    fetch = {
      type = "git";
      url = "https://github.com/projectcalico/go-json";
      rev = "6219dc7339ba20ee4c57df0a8baac62317d19cb1";
      sha256 = "0j6kgw7m6p51c3xz6ijdsr7lc965jbb12dxvz48ykw4in7gkbs22";
    };
  }
  {
    goPackagePath = "github.com/projectcalico/go-yaml";
    fetch = {
      type = "git";
      url = "https://github.com/projectcalico/go-yaml";
      rev = "955bc3e451ef0c9df8b9113bf2e341139cdafab2";
      sha256 = "0pjd4a428dhfm05y49gq2s52kpzw2fxcbywgjp5gzhwd8p673058";
    };
  }
  {
    goPackagePath = "github.com/projectcalico/go-yaml-wrapper";
    fetch = {
      type = "git";
      url = "https://github.com/projectcalico/go-yaml-wrapper";
      rev = "598e54215bee41a19677faa4f0c32acd2a87eb56";
      sha256 = "0mavpj911fzxxi486q9s7fnkwqsd99xdh4wdnaiixhmqdvs6lxbg";
    };
  }
  {
    goPackagePath = "github.com/projectcalico/libcalico-go";
    fetch = {
      type = "git";
      url = "https://github.com/projectcalico/libcalico-go";
      rev = "0417ab6e1ea49be2abb978df365b25f20fdb3c6f";
      sha256 = "1ifcmk9cwzkbsrka4izbafhgjwyss55kpj1aqyg8ypw9bn5wykrs";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_golang";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_golang";
      rev = "5cec1d0429b02e4323e042eb04dafdb079ddf568";
      sha256 = "1cgd5pcxf4zgcafq284yf2i711m3kddpb05prxy51li5p1l5cbq0";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_model";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_model";
      rev = "6f3806018612930941127f2a7c6c453ba2c527d2";
      sha256 = "1413ibprinxhni51p0755dp57r9wvbw7xgj9nmdaxmhzlqhc86j4";
    };
  }
  {
    goPackagePath = "github.com/prometheus/common";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/common";
      rev = "e3fb1a1acd7605367a2b378bc2e2f893c05174b7";
      sha256 = "1d9y4kkrfw6pqf0vrdd0k8a5mz4wx9gz15gl707cvszfnfrf40yp";
    };
  }
  {
    goPackagePath = "github.com/prometheus/procfs";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/procfs";
      rev = "f98634e408857669d61064b283c4cde240622865";
      sha256 = "098r6x3b1vawp69scz0z9drrx9pdz1a8f7nimqgw26wm39cms15w";
    };
  }
  {
    goPackagePath = "github.com/satori/go.uuid";
    fetch = {
      type = "git";
      url = "https://github.com/satori/go.uuid";
      rev = "f58768cc1a7a7e77a3bd49e98cdd21419399b6a3";
      sha256 = "1j4s5pfg2ldm35y8ls8jah4dya2grfnx2drb4jcbjsyrp4cm5yfb";
    };
  }
  {
    goPackagePath = "github.com/sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/sirupsen/logrus";
      rev = "d682213848ed68c0a260ca37d6dd5ace8423f5ba";
      sha256 = "0nzyqwzx3k7nqfq8q7yv32gaf3ymq3bpwhkmw1hj2zakq5a93d8x";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "9ff6c6923cfffbcd502984b8e0c80539a94968b7";
      sha256 = "0mfrxzyl8x7araa126lh8l3sihbbgfbzgkrg3v3cx7y4n3wrsqvn";
    };
  }
  {
    goPackagePath = "github.com/ugorji/go";
    fetch = {
      type = "git";
      url = "https://github.com/ugorji/go";
      rev = "bdcc60b419d136a85cdf2e7cbcac34b3f1cd6e57";
      sha256 = "0kv2z5m73d9bf7c0pr612kbb2wkbkl5z6jindsdfxbqa9d1scdsf";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "9419663f5a44be8b34ca85f08abc5fe1be11f8a3";
      sha256 = "07311hinf7g4dgba7rnmrxpjq7lhsqby50xjiwwda7c501hgwqcm";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "66aacef3dd8a676686c7ae3716979581e8b03c47";
      sha256 = "1dz4ngdicsnl378pdv4fr8p0q83vxdsn8x9lf82nds16mhsxg18x";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "a6bd8cefa1811bd24b86f8902872e4e8225f74c4";
      sha256 = "151in8qcf5y97ziavl6b03vgw4r87zqx5kg4vjhjszjbh60cfswp";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "ebfc5b4631820b793c9010c87fd8fef0f39eb082";
      sha256 = "001qxa0hqwpqwr4lwvlzs3yh71rh3hzwzmz3qfcszy4n2p91d5y9";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "b19bf474d317b857955b12035d2c5acb57ce8b01";
      sha256 = "0wc8csaafp0ps9jb2hdk8d6xpyw1axhk1np73h0z17x09zk3ylcr";
    };
  }
  {
    goPackagePath = "google.golang.org/genproto";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-genproto";
      rev = "09f6ed296fc66555a25fe4ce95173148778dfa85";
      sha256 = "06x5wr7vjsnvv35rpv7jaklilksqbzsbqk8bxababw8vr6avfwki";
    };
  }
  {
    goPackagePath = "google.golang.org/grpc";
    fetch = {
      type = "git";
      url = "https://github.com/grpc/grpc-go";
      rev = "5b3c4e850e90a4cf6a20ebd46c8b32a0a3afcb9e";
      sha256 = "1sf3fvphz16pf7jbm86n07rip9m5fh40wjcc2j2d5zpka36xvjw4";
    };
  }
  {
    goPackagePath = "gopkg.in/go-playground/validator.v8";
    fetch = {
      type = "git";
      url = "https://gopkg.in/go-playground/validator.v8";
      rev = "5f57d2222ad794d0dffb07e664ea05e2ee07d60c";
      sha256 = "1z40cblaq7mi573ikp95dl81q26v0lqqbw8v25pmryzgg4a1rfbx";
    };
  }
  {
    goPackagePath = "gopkg.in/inf.v0";
    fetch = {
      type = "git";
      url = "https://gopkg.in/inf.v0";
      rev = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4";
      sha256 = "0rf3vwyb8aqnac9x9d6ax7z5526c45a16yjm2pvkijr6qgqz8b82";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b";
      sha256 = "1hj2ag9knxflpjibck0n90jrhsrqz7qvad4qnif7jddyapi9bqzl";
    };
  }
  {
    goPackagePath = "k8s.io/api";
    fetch = {
      type = "git";
      url = "https://github.com/kubernetes/api";
      rev = "a315a049e7a93e5455f7fefce1ba136d85054687";
      sha256 = "06v2z2qzif3shnaklrj72jm2s1wkjzhhdq4bd6mx2brwlqfv1x8q";
    };
  }
  {
    goPackagePath = "k8s.io/apimachinery";
    fetch = {
      type = "git";
      url = "https://github.com/kubernetes/apimachinery";
      rev = "40eaf68ee1889b1da1c528b1a075ecfe94e66837";
      sha256 = "0kvkfn4axv34hny5a4w1fa2bqiy6a9d48gi1xlrpvyszrs83ivbk";
    };
  }
  {
    goPackagePath = "k8s.io/apiserver";
    fetch = {
      type = "git";
      url = "https://github.com/kubernetes/apiserver";
      rev = "7001bc4df8883d4a0ec84cd4b2117655a0009b6c";
      sha256 = "1vhbpj6f252gghclshqj5lsnv7bq8k78rgphdj2fg33ghbp2slcp";
    };
  }
  {
    goPackagePath = "k8s.io/client-go";
    fetch = {
      type = "git";
      url = "https://github.com/kubernetes/client-go";
      rev = "82aa063804cf055e16e8911250f888bc216e8b61";
      sha256 = "1l8dakfsawgxhiaqq0k9360gl13vr44sbjdxf7sbg3pl2csmi6pf";
    };
  }
  {
    goPackagePath = "k8s.io/kube-openapi";
    fetch = {
      type = "git";
      url = "https://github.com/kubernetes/kube-openapi";
      rev = "61b46af70dfed79c6d24530cd23b41440a7f22a5";
      sha256 = "09g2qv39m3lq694234yfxspwsx1jpmjv8qc519b57fqdaq8c8857";
    };
  }
]
