# DO NOT EDIT
# This file has been generated by
# $ tools/sources-from-github.sh

{pkgs}:
{
  # Head of branch R3.2-cloudwatt of repository github.com/cloudwatt/contrail-controller at 2017-10-12 12:38:45
  controller = pkgs.fetchFromGitHub {
    owner = "cloudwatt";
    repo = "contrail-controller";
    rev = "a1c686a444c16866c1a526ed5af3c124d930c705";
    sha256 = "12n1fx4r5hlkayvqgvynr4ssjfa8gps56czzigp2fcjg91ygc7yl";
  };
  # Head of branch master of repository github.com/cloudwatt/contrail-neutron-plugin at 2017-10-12 12:39:00
  neutronPlugin = pkgs.fetchFromGitHub {
    owner = "cloudwatt";
    repo = "contrail-neutron-plugin";
    rev = "91a10d261184fec7bde8d9413f53151b094a64f1";
    sha256 = "1c6rsgg6ld6mbg9x331chg2bwxwyagicnjpppm83qgak4i71v1vx";
  };
