# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "vault-fernet-locksmith-${version}";
  version = "0.1.0" ;
  rev = "v"+ version ;

  goPackagePath = "github.com/aevox/vault-fernet-locksmith";

  src = fetchFromGitHub {
    inherit rev;
    owner = "aevox";
    repo = "vault-fernet-locksmith";
    sha256 = "0q8sl6nd956hsh7bdnblydy1n2ql7fl9jcrl3zxgbcwb50rz293a";
  };

  buildFlagsArray = ''
    -ldflags= -X main.locksmithVersion=v${version}'';

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
