# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "vault-fernet-locksmith-${version}";
  version = "0.2.0" ;
  rev = "v"+ version ;

  goPackagePath = "github.com/aevox/vault-fernet-locksmith";

  src = fetchFromGitHub {
    inherit rev;
    owner = "aevox";
    repo = "vault-fernet-locksmith";
    sha256 = "1s1i98xwk8a0krvpwif0s3hgg8n77j58p8836864sf2yjdl13c0d";
  };

  buildFlagsArray = ''
    -ldflags= -X main.locksmithVersion=v${version}'';

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
