# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "kubernetes-flexvolume-vault-plugin-${version}";
  version = "2018-07-31";

  goPackagePath = "github.com/cloudwatt/kubernetes-flexvolume-vault-plugin";

  src = fetchgit {
    rev = "8eace64170b3ff1af8b13d54817087f28d935b34";
    url = "https://github.com/cloudwatt/kubernetes-flexvolume-vault-plugin.git";
    sha256 = "1jkccrhgq3ywx43lg3cf7w1s31pcsqli23zpn1bbayp6xfn1km62";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
