# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "github.com/Songmu/prompter";
    fetch = {
      type = "git";
      url = "https://github.com/Songmu/prompter";
      rev = "b5721e8d556682bcef33262731d98a39dee14dc4";
      sha256 = "0pqxxcr53zsg2vhgq3n407n0gcgl91n2mmcn228yqiw9mhhkii89";
    };
  }
  {
    goPackagePath = "github.com/fatih/structs";
    fetch = {
      type = "git";
      url = "https://github.com/fatih/structs";
      rev = "a720dfa8df582c51dee1b36feabb906bde1588bd";
      sha256 = "040grl40gcqd1y852lnf0l1l5wi73g0crnaihzl0nfsas9ydk3h4";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/errwrap";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/errwrap";
      rev = "7554cd9344cec97297fa6649b055a8c98c2a1e55";
      sha256 = "0kmv0p605di6jc8i1778qzass18m0mv9ks9vxxrfsiwcp4la82jf";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-cleanhttp";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-cleanhttp";
      rev = "3573b8b52aa7b37b9358d966a898feb387f62437";
      sha256 = "1pbl6p7w5wp1c70x7fp94h4ynk2ajfa76rqin3d2hq1w2fcb7byr";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-multierror";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-multierror";
      rev = "ed905158d87462226a13fe39ddf685ea65f1c11f";
      sha256 = "1bldhx9dmx9q4gjsag3g1xswq1jsf394rs69fdbmgnkj75j3sp70";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-rootcerts";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-rootcerts";
      rev = "6bb64b370b90e7ef1fa532be9e591a81c3493e00";
      sha256 = "1a81fcm1i0ji2iva0dcimiichgwpbcb7lx0vyaks87zj5wf04qy9";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "392dba7d905ed5d04a5794ba89f558b27e2ba1ca";
      sha256 = "1rfm67kma2hpakabf7hxlj196jags4rpjpcirwg4kan4g9b6j0kb";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/vault";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/vault";
      rev = "d28dd5a018294562dbc9a18c95554d52b5d12390";
      sha256 = "1kclpyb9a9y5zjvrlbxnkac4fl3lwqsr98v4yydf9ihl5v7wy4f5";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "fc9e8d8ef48496124e79ae0df75490096eccf6fe";
      sha256 = "1r5f9gkavkb1w6sr0qs5kj16706xirl3qnlq3hqpszkw9w27x65a";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "b8bc1bf767474819792c23f32d8286a45736f1c6";
      sha256 = "13ry4lylalkh4g2vny9cxwvryslzyzwp9r92z0b10idhdq3wad1q";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "cc8532a8e9a55ea36402aa21efdf403a60d34096";
      sha256 = "0705c0hq7b993sabnjy65yymvpy9w1j84bg9bjczh5607z16nw86";
    };
  }
  {
    goPackagePath = "github.com/sethgrid/pester";
    fetch = {
      type = "git";
      url = "https://github.com/sethgrid/pester";
      rev = "4f4c0a67b6496764028e1ab9fd8dfb630282ed2f";
      sha256 = "0wachd85malsgi8l8541kjvdnc1sbxna090xjx75a08m31x6l8zd";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "ab89591268e0c8b748cbe4047b00197516011af5";
      sha256 = "1cbg8wlv1hmdps9ksa4kym5zy0mb2yjykw4ns7yqv7nmz4s5xajr";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "f2499483f923065a842d38eb4c7f1927e6fc6e6d";
      sha256 = "0q1ps8igfczfafk39hkp8gs57s6qxjvf2c48hiq00p873agz0x7s";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "1e99a4f9d247b28c670884b9a8d6801f39a47b77";
      sha256 = "1m1yma11j0ncx4fsihqcwvr30va2ll8ixajdc2if5y3n3k0iv29m";
    };
  }
]
