#!/usr/bin/env bash

vm=1
for vrouter in vrouter-master vrouter
do
  ip="$(curl -s localhost:8500/v1/catalog/service/opencontrail-$vrouter | jq -r .[].ServiceAddress)"
  ssh -q -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" root@$ip "netns-daemon-start -n default-domain:default-project:vn1 -s api vm${vm}0"
  ((vm++))
done

# ping from vrouter-master to vrouter
ip="$(curl -s localhost:8500/v1/catalog/service/opencontrail-vrouter | jq -r .[].ServiceAddress)"
add=$(ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" root@$ip 'ip netns exec ns-vm20 ip a  | grep "inet\b" | awk '\''{print $2}'\'' | cut -d/ -f1')

ip="$(curl -s localhost:8500/v1/catalog/service/opencontrail-vrouter-master | jq -r .[].ServiceAddress)"
ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" root@$ip ip netns exec ns-vm10 ping -c 2 $add  &> /dev/null && echo "ping success" || echo "ping failed"
