# This is a quick and dirty expression to get Pileus. This would not
# work well with proxies on the CI (a GEM cache should be generated by
# another expressions with a fixed hash).
#
# To build it:
# nix-build -E 'with import <nixpkgs> { }; callPackage pkgs/pileus {}'

{ stdenv, ruby, zlib, makeWrapper }:

stdenv.mkDerivation rec {
  name = "pileus";
  buildInputs = [ ruby zlib makeWrapper ];
  phases = [ "buildPhase" "installPhase" "fixupPhase"];
  buildPhase = ''
    GEM_HOME=$PWD gem install -N --no-ri -s http://gems.corp.cloudwatt.com pileus
  '';
  installPhase = ''
    mkdir $out
    rm -rf *.gem cache/
    # We only keep pileus in bin to avoid collisions with upstream
    # packages such as chef.
    find bin/ -not -name pileus -exec rm '{}' \;
    cp -r ./* $out/
  '';
  postFixup = "wrapProgram $out/bin/pileus --set GEM_HOME $out";
}
