# DO NOT EDIT
# This file has been generated by
# $ ./tools/sources-from-github.sh

{pkgs}:
{
  # Head of branch R3.2-cloudwatt of repository github.com/cloudwatt/contrail-controller at 2018-01-26 10:53:37
  controller = pkgs.fetchFromGitHub {
    owner = "cloudwatt";
    repo = "contrail-controller";
    rev = "ef73f51d1a5daea2f9875345bdf34b9a7c8b6cb2";
    sha256 = "0pk2nid2l6l00f9d6gb2a9icahsmlhlb01k294925pn5rsffz6k6";
  };
  # Head of branch master of repository github.com/cloudwatt/contrail-neutron-plugin at 2018-01-26 10:53:55
  neutronPlugin = pkgs.fetchFromGitHub {
    owner = "cloudwatt";
    repo = "contrail-neutron-plugin";
    rev = "91a10d261184fec7bde8d9413f53151b094a64f1";
    sha256 = "1c6rsgg6ld6mbg9x331chg2bwxwyagicnjpppm83qgak4i71v1vx";
  };
  # Head of branch R3.2-cloudwatt of repository github.com/nlewo/contrail-vrouter at 2018-01-26 10:53:57
  vrouter = pkgs.fetchFromGitHub {
    owner = "nlewo";
    repo = "contrail-vrouter";
    rev = "005b2af10aa8ad5819e123f9ef596041dba8db5d";
    sha256 = "0pk8vhgskjnr9914n49ilzvpxiwxabmsf3cd8zqn80s4pkhbd78w";
  };
}
