#!/usr/bin/env bash

# A script that generates a sources.nix skeleton by looking for the latest
# commit in the specified branch on the Cloudwatt gitlab repository
#
# Usage: ./sources.sh


# The format of this file is
# Attribute Repos Branch
cat >/tmp/tmp.lst <<EOF
build contrail-build R3.2
controller contrail-controller R3.2-cloudwatt
generateds contrail-generateds R3.2-cloudwatt
neutronPlugin contrail-neutron-plugin master
sandesh contrail-sandesh R3.2
thirdParty contrail-third-party R3.2
vrouter contrail-vrouter R3.2-cloudwatt
webController contrail-web-controller R3.2
webCore contrail-web-core R3.2
webuiThirdParty contrail-webui-third-party R3.2
EOF

echo "# DO NOT EDIT"
echo "# This file has been generated by"
echo "# $ $0"
echo
echo "{pkgs}:"
echo "{"

while read -r ATTRIBUTE REPOS BRANCH; do
    echo "  # Head of branch $BRANCH of repository $REPOS at $(date +'%F %T')"
    COMMITID=$(curl -Ls "https://git.corp.cloudwatt.com/api/v4/projects/applications%2F${REPOS}/repository/commits/${BRANCH}" | jq -r .id)
    if [ $COMMITID == "null" ]; then
	echo
	echo "Branch $BRANCH of repository $REPOS can be fetched... exiting."
	exit 1
    fi
    URL="https://git.corp.cloudwatt.com/applications/$REPOS/repository/archive.tar.gz?ref=$COMMITID"
    curl --silent -L $URL > /tmp/archive.tgz

    rm -rf /tmp/untar.tmp/
    mkdir /tmp/untar.tmp
    tar -C /tmp/untar.tmp/ -xf /tmp/archive.tgz
    SHA256=$(find /tmp/untar.tmp/ -maxdepth 1 -mindepth 1 -exec nix-hash --type sha256 --base32 '{}' \;)

    echo "  $ATTRIBUTE = pkgs.fetchzip {"
    echo "    name = \"$REPOS.$BRANCH\";"
    echo "    url = \"$URL\";"
    echo "    sha256 = \"$SHA256\";"
    echo "  };"
    echo
done < /tmp/tmp.lst

echo "}"

rm -f /tmp/archive.tgz
rm -f /tmp/tmp.lst
rm -rf /tmp/untar.tmp


