# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
{ pkgs, stdenv, buildGo110Package, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGo110Package rec {
  name = "cni-plugin-${version}";
  version = "3.1.3";

  goPackagePath = "github.com/projectcalico/cni-plugin";

  outputs = [ "out" "bin" "plugins" ];

  src = fetchgit {
    rev = "c6d733d40c9306e40a61c0a80a9bfecbf05861d5";
    url = "https://github.com/projectcalico/cni-plugin.git";
    sha256 = "0kdp8kcycqs2k0fb06j4mscwii2mgrnhnwkz7ss6b094gyj9fv8q";
  };

  buildPhase = ''
    rm -rf $NIX_BUILD_TOP/go/src/github.com/containernetworking/plugins/vendor/
    cd $NIX_BUILD_TOP/go/src/github.com/projectcalico/cni-plugin
	go build -v -i -o $NIX_BUILD_TOP/go/bin/calico calico.go
	go build -v -i -o $NIX_BUILD_TOP/go/bin/calico-ipam ipam/calico-ipam.go
  '';

  # we need a 'plugins' output for kubernetes module
  postInstall = ''
    mkdir -p $plugins
    cp $bin/bin/* $plugins/
  '';
  preFixup = ''
    find $plugins -type f -exec remove-references-to -t ${pkgs.go} '{}' + || true
  '';

  goDeps = ./deps.nix;

}
