# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "cloud.google.com/go";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/gocloud";
      rev = "3b1ae45394a234c385be014e9a488f2bb6eef821";
      sha256 = "0alb495ql6s02kb6lxcbnlkdcmhixyl8zv11sgrkhsk1bckzh119";
    };
  }
  {
    goPackagePath = "github.com/Azure/go-autorest";
    fetch = {
      type = "git";
      url = "https://github.com/Azure/go-autorest";
      rev = "58f6f26e200fa5dfb40c9cd1c83f3e2c860d779d";
      sha256 = "06zzkw0x8sv57x0fi0chcn9zm5qq69spbsa02d0zdlzh2bd74x6f";
    };
  }
  {
    goPackagePath = "github.com/PuerkitoBio/purell";
    fetch = {
      type = "git";
      url = "https://github.com/PuerkitoBio/purell";
      rev = "8a290539e2e8629dbc4e6bad948158f790ec31f4";
      sha256 = "1qhsy1nm96b9kb63svkvkqmmw15xg6irwcysisxdgzk64adfwqv1";
    };
  }
  {
    goPackagePath = "github.com/PuerkitoBio/urlesc";
    fetch = {
      type = "git";
      url = "https://github.com/PuerkitoBio/urlesc";
      rev = "5bd2802263f21d8788851d5305584c82a5c75d7e";
      sha256 = "15y5r3asvm7196m3nza5xvdvlc2k11p6lfs6hi917hl7r9vgi6mp";
    };
  }
  {
    goPackagePath = "github.com/beorn7/perks";
    fetch = {
      type = "git";
      url = "https://github.com/beorn7/perks";
      rev = "3a771d992973f24aa725d07868b467d1ddfceafb";
      sha256 = "1l2lns4f5jabp61201sh88zf3b0q793w4zdgp9nll7mmfcxxjif3";
    };
  }
  {
    goPackagePath = "github.com/containernetworking/cni";
    fetch = {
      type = "git";
      url = "https://github.com/containernetworking/cni";
      rev = "a2da8f8d7fd8e6dc25f336408a8ac86f050fbd88";
      sha256 = "11zn9cbp484l09d5kfs2ys9ml1v7syqvqqv8v1v35zvcx4snllv2";
    };
  }
  {
    goPackagePath = "github.com/containernetworking/plugins";
    fetch = {
      type = "git";
      url = "https://github.com/containernetworking/plugins";
      rev = "7480240de9749f9a0a5c8614b17f1f03e0c06ab9";
      sha256 = "0lb61j8h5fbi45dlc77y855warc323dybb12ncw0npaq0i34l5ay";
    };
  }
  {
    goPackagePath = "github.com/coreos/etcd";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/etcd";
      rev = "c23606781f63d09917a1e7abfcefeb337a9608ea";
      sha256 = "0fgwidy7kbsynxz9q7bkrh56s29yg32ik6vibdlsy78xdda9mlwm";
    };
  }
  {
    goPackagePath = "github.com/coreos/go-iptables";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/go-iptables";
      rev = "b5b1876b170881a8259f036445ee89c8669db386";
      sha256 = "1s1c04x47pk3168606x4vkg4avs8a7m407hpha8py1xni08cgb6m";
    };
  }
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "782f4967f2dc4564575ca782fe2d04090b5faca8";
      sha256 = "1ypijjawqc0xgmgim42260ibcyclfgfizicz5cbvndw4plqfsswk";
    };
  }
  {
    goPackagePath = "github.com/dgrijalva/jwt-go";
    fetch = {
      type = "git";
      url = "https://github.com/dgrijalva/jwt-go";
      rev = "01aeca54ebda6e0fbfafd0a524d234159c05ec20";
      sha256 = "10dmb5xxn5wijn299h483z0klprprkq7n1azakm3ysp50sr11ywg";
    };
  }
  {
    goPackagePath = "github.com/emicklei/go-restful";
    fetch = {
      type = "git";
      url = "https://github.com/emicklei/go-restful";
      rev = "ff4f55a206334ef123e4f79bbf348980da81ca46";
      sha256 = "1v5lj5142abz3gvbygp6xghpdx4ps2lwswl8559ivaidahwnc21c";
    };
  }
  {
    goPackagePath = "github.com/emicklei/go-restful-swagger12";
    fetch = {
      type = "git";
      url = "https://github.com/emicklei/go-restful-swagger12";
      rev = "dcef7f55730566d41eae5db10e7d6981829720f6";
      sha256 = "0zz1f6n1qfbyrp592mgyrkyfhki3r0ksic6ja9lxisg8br1ibrvq";
    };
  }
  {
    goPackagePath = "github.com/ghodss/yaml";
    fetch = {
      type = "git";
      url = "https://github.com/ghodss/yaml";
      rev = "73d445a93680fa1a78ae23a5839bad48f32ba1ee";
      sha256 = "0pg53ky4sy3sp9j4n7vgf1p3gw4nbckwqfldcmmi9rf13kjh0mr7";
    };
  }
  {
    goPackagePath = "github.com/go-openapi/jsonpointer";
    fetch = {
      type = "git";
      url = "https://github.com/go-openapi/jsonpointer";
      rev = "46af16f9f7b149af66e5d1bd010e3574dc06de98";
      sha256 = "0w0fphmdycjzbsm1vppdcjc9aqinkcdzcq3pxikdvdqh5p791gsc";
    };
  }
  {
    goPackagePath = "github.com/go-openapi/jsonreference";
    fetch = {
      type = "git";
      url = "https://github.com/go-openapi/jsonreference";
      rev = "13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272";
      sha256 = "1fh4xcl9ijww4bdq656sx981d57w2c9zx5148jsxlsg4bsvxmwis";
    };
  }
  {
    goPackagePath = "github.com/go-openapi/spec";
    fetch = {
      type = "git";
      url = "https://github.com/go-openapi/spec";
      rev = "6aced65f8501fe1217321abf0749d354824ba2ff";
      sha256 = "0yf0nw7167yjpiqrikns5djarjpf2r07q6xnq9xb1cfsc4m7ynm4";
    };
  }
  {
    goPackagePath = "github.com/go-openapi/swag";
    fetch = {
      type = "git";
      url = "https://github.com/go-openapi/swag";
      rev = "1d0bd113de87027671077d3c71eb3ac5d7dbba72";
      sha256 = "0fmk42chj20679n87n6sig3czs25lavyj6w208000n6kccv1ns3c";
    };
  }
  {
    goPackagePath = "github.com/gogo/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/gogo/protobuf";
      rev = "c0656edd0d9eab7c66d1eb0c568f9039345796f7";
      sha256 = "0b943dhx571lhgcs3rqzy0092mi2x5mwy2kl7g8rryhy3r5rzrz9";
    };
  }
  {
    goPackagePath = "github.com/golang/glog";
    fetch = {
      type = "git";
      url = "https://github.com/golang/glog";
      rev = "44145f04b68cf362d9c4df2182967c2275eaefed";
      sha256 = "1k7sf6qmpgm0iw81gx2dwggf9di6lgw0n54mni7862hihwfrb5rq";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "4bd1920723d7b7c925de087aa32e2187708897f7";
      sha256 = "0z21hxin616xvkv075vdz416zm36qs0mbi76526l9yz8khbg7jmr";
    };
  }
  {
    goPackagePath = "github.com/google/btree";
    fetch = {
      type = "git";
      url = "https://github.com/google/btree";
      rev = "7d79101e329e5a3adf994758c578dab82b90c017";
      sha256 = "1c1hsy5s2pfawg3l9954jmqmy4yc2zp3f7i87m00km2yqgb8xpd0";
    };
  }
  {
    goPackagePath = "github.com/google/gofuzz";
    fetch = {
      type = "git";
      url = "https://github.com/google/gofuzz";
      rev = "44d81051d367757e1c7c6a5a86423ece9afcf63c";
      sha256 = "0ivq2sl2fv8x0xxrcys27c42s8yq7irgl7lp6l0im9i7ky63nk0i";
    };
  }
  {
    goPackagePath = "github.com/googleapis/gnostic";
    fetch = {
      type = "git";
      url = "https://github.com/googleapis/gnostic";
      rev = "0c5108395e2debce0d731cf0287ddf7242066aba";
      sha256 = "0jf3cp5clli88gpjf24r6wxbkvngnc1kf59d4cgjczsn2wasvsfc";
    };
  }
  {
    goPackagePath = "github.com/gophercloud/gophercloud";
    fetch = {
      type = "git";
      url = "https://github.com/gophercloud/gophercloud";
      rev = "2bf16b94fdd9b01557c4d076e567fe5cbbe5a961";
      sha256 = "0l4xnmq2nwnxfzqr49vmacmpbhrvnp21k1hdm8p8hc05a9x2jp4v";
    };
  }
  {
    goPackagePath = "github.com/gregjones/httpcache";
    fetch = {
      type = "git";
      url = "https://github.com/gregjones/httpcache";
      rev = "787624de3eb7bd915c329cba748687a3b22666a6";
      sha256 = "1zqlg9pkj7r6fqw7wv3ywvbz3bh0hvzifs2scgcraj812q5189w5";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/golang-lru";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/golang-lru";
      rev = "a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4";
      sha256 = "1z3h4aca31l3qs0inqr5l49vrlycpjm7vq1l9nh1mp0mb2ij0kmp";
    };
  }
  {
    goPackagePath = "github.com/howeyc/gopass";
    fetch = {
      type = "git";
      url = "https://github.com/howeyc/gopass";
      rev = "bf9dde6d0d2c004a008c27aaee91170c786f6db8";
      sha256 = "1jxzyfnqi0h1fzlsvlkn10bncic803bfhslyijcxk55mgh297g45";
    };
  }
  {
    goPackagePath = "github.com/imdario/mergo";
    fetch = {
      type = "git";
      url = "https://github.com/imdario/mergo";
      rev = "6633656539c1639d9d78127b7d47c622b5d7b6dc";
      sha256 = "1fffbq1l17i0gynmvcxypl7d9h4v81g5vlimiph5bfgf4sp4db7g";
    };
  }
  {
    goPackagePath = "github.com/json-iterator/go";
    fetch = {
      type = "git";
      url = "https://github.com/json-iterator/go";
      rev = "36b14963da70d11297d313183d7e6388c8510e1e";
      sha256 = "143sz8ld4w3798iwdg1wxyqdks3wskdasy3fhrzfnqx1ayifr3fh";
    };
  }
  {
    goPackagePath = "github.com/juju/ratelimit";
    fetch = {
      type = "git";
      url = "https://github.com/juju/ratelimit";
      rev = "5b9ff866471762aa2ab2dced63c9fb6f53921342";
      sha256 = "12fsx3wqg49wisigbybdzic7gc2p5a0fk55714mpv7zq8jr6i46k";
    };
  }
  {
    goPackagePath = "github.com/kelseyhightower/envconfig";
    fetch = {
      type = "git";
      url = "https://github.com/kelseyhightower/envconfig";
      rev = "f611eb38b3875cc3bd991ca91c51d06446afa14c";
      sha256 = "1zcq480ig7wbg4378qcfxznp2gzqmk7x6rbxizflvg9v2f376vrw";
    };
  }
  {
    goPackagePath = "github.com/mailru/easyjson";
    fetch = {
      type = "git";
      url = "https://github.com/mailru/easyjson";
      rev = "d5b7844b561a7bc640052f1b935f7b800330d7e0";
      sha256 = "1g84l4wns28xjpn6nl1g33dcj3sfgxlkqqsa6w8fbq2kwyd50xka";
    };
  }
  {
    goPackagePath = "github.com/matttproud/golang_protobuf_extensions";
    fetch = {
      type = "git";
      url = "https://github.com/matttproud/golang_protobuf_extensions";
      rev = "c12348ce28de40eed0136aa2b644d0ee0650e56c";
      sha256 = "1d0c1isd2lk9pnfq2nk0aih356j30k3h1gi2w0ixsivi5csl7jya";
    };
  }
  {
    goPackagePath = "github.com/mcuadros/go-version";
    fetch = {
      type = "git";
      url = "https://github.com/mcuadros/go-version";
      rev = "88e56e02bea1c203c99222c365fa52a69996ccac";
      sha256 = "02m801x7rj4ra9xg8qgbn68xls998zwv29fx55kla40bz7wq7035";
    };
  }
  {
    goPackagePath = "github.com/onsi/ginkgo";
    fetch = {
      type = "git";
      url = "https://github.com/onsi/ginkgo";
      rev = "fa5fabab2a1bfbd924faf4c067d07ae414e2aedf";
      sha256 = "1q6431prnrarwlg4p7bfzn64rbx40n91j8673jmzmmbnp28qvskb";
    };
  }
  {
    goPackagePath = "github.com/onsi/gomega";
    fetch = {
      type = "git";
      url = "https://github.com/onsi/gomega";
      rev = "62bff4df71bdbc266561a0caee19f0594b17c240";
      sha256 = "12rpmq7vx2p7wzrqbk1cs655rpip4kja2csi3halpn8x6bk1xjj4";
    };
  }
  {
    goPackagePath = "github.com/pborman/uuid";
    fetch = {
      type = "git";
      url = "https://github.com/pborman/uuid";
      rev = "ca53cad383cad2479bbba7f7a1a05797ec1386e4";
      sha256 = "0rcx669bbjkkwdlw81spnra4ffgzd4rbpywnrj3w41m9vq6mk1gn";
    };
  }
  {
    goPackagePath = "github.com/petar/GoLLRB";
    fetch = {
      type = "git";
      url = "https://github.com/petar/GoLLRB";
      rev = "53be0d36a84c2a886ca057d34b6aa4468df9ccb4";
      sha256 = "01xp3lcamqkvl91jg6ly202gdsgf64j39rkrcqxi6v4pbrcv7hz0";
    };
  }
  {
    goPackagePath = "github.com/peterbourgon/diskv";
    fetch = {
      type = "git";
      url = "https://github.com/peterbourgon/diskv";
      rev = "5f041e8faa004a95c88a202771f4cc3e991971e6";
      sha256 = "1mxpa5aad08x30qcbffzk80g9540wvbca4blc1r2qyzl65b8929b";
    };
  }
  {
    goPackagePath = "github.com/projectcalico/go-json";
    fetch = {
      type = "git";
      url = "https://github.com/projectcalico/go-json";
      rev = "6219dc7339ba20ee4c57df0a8baac62317d19cb1";
      sha256 = "0j6kgw7m6p51c3xz6ijdsr7lc965jbb12dxvz48ykw4in7gkbs22";
    };
  }
  {
    goPackagePath = "github.com/projectcalico/go-yaml";
    fetch = {
      type = "git";
      url = "https://github.com/projectcalico/go-yaml";
      rev = "955bc3e451ef0c9df8b9113bf2e341139cdafab2";
      sha256 = "0pjd4a428dhfm05y49gq2s52kpzw2fxcbywgjp5gzhwd8p673058";
    };
  }
  {
    goPackagePath = "github.com/projectcalico/go-yaml-wrapper";
    fetch = {
      type = "git";
      url = "https://github.com/projectcalico/go-yaml-wrapper";
      rev = "598e54215bee41a19677faa4f0c32acd2a87eb56";
      sha256 = "0mavpj911fzxxi486q9s7fnkwqsd99xdh4wdnaiixhmqdvs6lxbg";
    };
  }
  {
    goPackagePath = "github.com/projectcalico/libcalico-go";
    fetch = {
      type = "git";
      url = "https://github.com/projectcalico/libcalico-go";
      rev = "0417ab6e1ea49be2abb978df365b25f20fdb3c6f";
      sha256 = "1ifcmk9cwzkbsrka4izbafhgjwyss55kpj1aqyg8ypw9bn5wykrs";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_golang";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_golang";
      rev = "967789050ba94deca04a5e84cce8ad472ce313c1";
      sha256 = "1djwz6shmyx5kbp9b1pim3kncq2jwn3qhbx4b0b4lq7msww76hpz";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_model";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_model";
      rev = "99fa1f4be8e564e8a6b613da7fa6f46c9edafc6c";
      sha256 = "19y4ywsivhpxj7ikf2j0gm9k3cmyw37qcbfi78n526jxcc7kw998";
    };
  }
  {
    goPackagePath = "github.com/prometheus/common";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/common";
      rev = "7600349dcfe1abd18d72d3a1770870d9800a7801";
      sha256 = "0lsp94dqpj35dny4m4x15kg4wgwawlm3in7cnpajkkacgyxagk5f";
    };
  }
  {
    goPackagePath = "github.com/prometheus/procfs";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/procfs";
      rev = "f98634e408857669d61064b283c4cde240622865";
      sha256 = "098r6x3b1vawp69scz0z9drrx9pdz1a8f7nimqgw26wm39cms15w";
    };
  }
  {
    goPackagePath = "github.com/satori/go.uuid";
    fetch = {
      type = "git";
      url = "https://github.com/satori/go.uuid";
      rev = "f58768cc1a7a7e77a3bd49e98cdd21419399b6a3";
      sha256 = "1j4s5pfg2ldm35y8ls8jah4dya2grfnx2drb4jcbjsyrp4cm5yfb";
    };
  }
  {
    goPackagePath = "github.com/sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/sirupsen/logrus";
      rev = "d682213848ed68c0a260ca37d6dd5ace8423f5ba";
      sha256 = "0nzyqwzx3k7nqfq8q7yv32gaf3ymq3bpwhkmw1hj2zakq5a93d8x";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "9ff6c6923cfffbcd502984b8e0c80539a94968b7";
      sha256 = "0mfrxzyl8x7araa126lh8l3sihbbgfbzgkrg3v3cx7y4n3wrsqvn";
    };
  }
  {
    goPackagePath = "github.com/vishvananda/netlink";
    fetch = {
      type = "git";
      url = "https://github.com/vishvananda/netlink";
      rev = "fe3b5664d23a11b52ba59bece4ff29c52772a56b";
      sha256 = "1vidqnd4a9k9nf206bwvbfli4w2swi089xs03300rc1l46qrn86n";
    };
  }
  {
    goPackagePath = "github.com/vishvananda/netns";
    fetch = {
      type = "git";
      url = "https://github.com/vishvananda/netns";
      rev = "8ba1072b58e0c2a240eb5f6120165c7776c3e7b8";
      sha256 = "1g35qwam7y4gvv1nfa6l27gzzv1wlj8m8f66d92ghsq76y54kcs1";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "1351f936d976c60a0a48d728281922cf63eafb8d";
      sha256 = "1vf4z97y7xnhzjizik0lghr7ip77hhdj9kbb35rr4c9sn108f20j";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "66aacef3dd8a676686c7ae3716979581e8b03c47";
      sha256 = "1dz4ngdicsnl378pdv4fr8p0q83vxdsn8x9lf82nds16mhsxg18x";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "a6bd8cefa1811bd24b86f8902872e4e8225f74c4";
      sha256 = "151in8qcf5y97ziavl6b03vgw4r87zqx5kg4vjhjszjbh60cfswp";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "076b546753157f758b316e59bcb51e6807c04057";
      sha256 = "1kwfzqfnp9kb7z5a2gpfmnpgnwkrv74z0gwpls1m6nc04hlg7kwc";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "b19bf474d317b857955b12035d2c5acb57ce8b01";
      sha256 = "0wc8csaafp0ps9jb2hdk8d6xpyw1axhk1np73h0z17x09zk3ylcr";
    };
  }
  {
    goPackagePath = "google.golang.org/appengine";
    fetch = {
      type = "git";
      url = "https://github.com/golang/appengine";
      rev = "b1f26356af11148e710935ed1ac8a7f5702c7612";
      sha256 = "1pz202zszg8f35dk5pfhwgcdi3r6dx1l4yk6x6ly7nb4j45zi96x";
    };
  }
  {
    goPackagePath = "google.golang.org/genproto";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-genproto";
      rev = "09f6ed296fc66555a25fe4ce95173148778dfa85";
      sha256 = "06x5wr7vjsnvv35rpv7jaklilksqbzsbqk8bxababw8vr6avfwki";
    };
  }
  {
    goPackagePath = "google.golang.org/grpc";
    fetch = {
      type = "git";
      url = "https://github.com/grpc/grpc-go";
      rev = "5b3c4e850e90a4cf6a20ebd46c8b32a0a3afcb9e";
      sha256 = "1sf3fvphz16pf7jbm86n07rip9m5fh40wjcc2j2d5zpka36xvjw4";
    };
  }
  {
    goPackagePath = "gopkg.in/go-playground/validator.v8";
    fetch = {
      type = "git";
      url = "https://gopkg.in/go-playground/validator.v8";
      rev = "5f57d2222ad794d0dffb07e664ea05e2ee07d60c";
      sha256 = "1z40cblaq7mi573ikp95dl81q26v0lqqbw8v25pmryzgg4a1rfbx";
    };
  }
  {
    goPackagePath = "gopkg.in/inf.v0";
    fetch = {
      type = "git";
      url = "https://gopkg.in/inf.v0";
      rev = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4";
      sha256 = "0rf3vwyb8aqnac9x9d6ax7z5526c45a16yjm2pvkijr6qgqz8b82";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "53feefa2559fb8dfa8d81baad31be332c97d6c77";
      sha256 = "1afspdzgq5p1803fnzjyx0is75vjbsxkj9wq1dgz5jcz4wi764hg";
    };
  }
  {
    goPackagePath = "k8s.io/api";
    fetch = {
      type = "git";
      url = "https://github.com/kubernetes/api";
      rev = "a315a049e7a93e5455f7fefce1ba136d85054687";
      sha256 = "06v2z2qzif3shnaklrj72jm2s1wkjzhhdq4bd6mx2brwlqfv1x8q";
    };
  }
  {
    goPackagePath = "k8s.io/apimachinery";
    fetch = {
      type = "git";
      url = "https://github.com/kubernetes/apimachinery";
      rev = "40eaf68ee1889b1da1c528b1a075ecfe94e66837";
      sha256 = "0kvkfn4axv34hny5a4w1fa2bqiy6a9d48gi1xlrpvyszrs83ivbk";
    };
  }
  {
    goPackagePath = "k8s.io/client-go";
    fetch = {
      type = "git";
      url = "https://github.com/kubernetes/client-go";
      rev = "82aa063804cf055e16e8911250f888bc216e8b61";
      sha256 = "1l8dakfsawgxhiaqq0k9360gl13vr44sbjdxf7sbg3pl2csmi6pf";
    };
  }
  {
    goPackagePath = "k8s.io/kube-openapi";
    fetch = {
      type = "git";
      url = "https://github.com/kubernetes/kube-openapi";
      rev = "0c329704159e3b051aafac400b15baacf2a94a04";
      sha256 = "01mizydrknrf6w787dib0dl60jlh1axzxnlf7ihrga5vwc56zp03";
    };
  }
]
