source "https://rubygems.org"

gem 'fluentd', '~> 0.14'
gem 'fluent-plugin-prometheus'
gem 'fluent-plugin-rewrite-tag-filter'
gem 'fluent-plugin-concat'
gem 'fluent-plugin-named_pipe'
gem 'fluent-plugin-detect-exceptions'
gem 'fluent-plugin-multi-format-parser'
